### ISSUE TITLE
Output as a LaTeX code

### ISSUE THREAD

**Issue by pj-mathematician** [kieferlam/postfixrenderer#1]
I am in search of an infix to LaTeX code converter, your postfix module was the best option I found which also took care of other operators like sqrt and trigonometric etc. Since this project directly returns the output using javafx, is there any way I can extract/convert the output to LaTeX code

**Comment by kieferlam** [comment]
If you can do it yourself, the best way would be to use the actual Infix -> Postfix conversion library that this project uses (https://github.com/kieferlam/postfix).

The `Expression` object from the Postfix library (link above) will give you the operations and values in the correct order and in postfix notation. So you can simply evaluate the postfix notation how you normally would (i.e. using a stack) but create a string with LaTeX math syntax instead. Similar to [this function in this project](https://github.com/kieferlam/postfixrenderer/blob/e8fb0901399773178ea48bda58c3dc9b716ac579/src/com/kieferlam/maths/fx/view/render/MathsRenderer.kt#L18) however instead of the render function, you would use your own 'render' function which outputs a string instead.

E.g. the [`FractionRenderer`](https://github.com/kieferlam/postfixrenderer/blob/master/src/com/kieferlam/maths/fx/view/render/operator/FractionRenderer.kt) takes 2 operands and draws them onto an image, however you may simply replace it with `\frac{operand[0]}{operand[1]}` where the resulting string will be added to the stack to be used with other operators if needed.

This seems like a fun little project so I might create a separate project myself when I have the time.

**Comment by pj-mathematician** [comment]
Thanks alot for the reply, your suggestion is really helpful. My problem is solved! Thanks again 👍🏻
